import requests
import os
import sys

def fetch_ability_generation(url, cache):
    if url in cache:
        return cache[url]
    
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        gen_name = data["generation"]["name"]
        cache[url] = gen_name
        return gen_name
    except Exception as e:
        print(f"Error fetching ability data from {url}: {e}", file=sys.stderr)
        return None

def fetch_pokemon_abilities(pokemon_id, ability_cache):
    print(f"Fetching abilities for Pokemon #{pokemon_id}...", file=sys.stderr)
    url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_id}"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        
        abilities = []
        # Sort by slot to maintain consistent order (slot 1, then slot 2)
        sorted_abilities = sorted(data["abilities"], key=lambda x: x["slot"])
        
        for ability_entry in sorted_abilities:
            if ability_entry["is_hidden"]:
                continue
                
            ability_name = ability_entry["ability"]["name"]
            ability_url = ability_entry["ability"]["url"]
            
            gen = fetch_ability_generation(ability_url, ability_cache)
            # Abilities were introduced in Generation 3. 
            # We ignore any ability introduced in Generation 4 or later.
            if gen == "generation-iii":
                abilities.append(ability_name)
        
        return abilities
    except Exception as e:
        print(f"Error fetching Pokemon #{pokemon_id}: {e}", file=sys.stderr)
        return None

def main():
    all_abilities = {}
    ability_cache = {}
    
    # Pokémon 1 to 386 (Generation 1-3)
    for i in range(1, 387):
        abilities = fetch_pokemon_abilities(i, ability_cache)
        if abilities is not None:
            all_abilities[i] = abilities
            
    output_path = "PokeCable/api/app/data/pokemon_abilities.py"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# This file was automatically generated by scripts/fetch_pokemon_abilities.py\n\n")
        f.write("SPECIES_ABILITIES: dict[int, list[str]] = {\n")
        for pkmn_id, abilities in sorted(all_abilities.items()):
            f.write(f"    {pkmn_id}: {repr(abilities)},\n")
        f.write("}\n")

    print(f"Successfully generated {output_path}")

if __name__ == "__main__":
    main()
