from __future__ import annotations

from .battle_pokemon import BattleMove


def normalize_move_name(value: str) -> str:
    return str(value or "").lower().replace("-", "").replace(" ", "")


HIGH_CRITICAL_MOVES = {
    "karate-chop",
    "razor-leaf",
    "crabhammer",
    "slash",
    "aeroblast",
    "cross-chop",
    "air-cutter",
    "leaf-blade",
}


CONTACT_MOVES = {
    "pound",
    "karate-chop",
    "double-slap",
    "comet-punch",
    "mega-punch",
    "fire-punch",
    "ice-punch",
    "thunder-punch",
    "scratch",
    "vice-grip",
    "guillotine",
    "cut",
    "wing-attack",
    "fly",
    "bind",
    "slam",
    "vine-whip",
    "stomp",
    "double-kick",
    "mega-kick",
    "jump-kick",
    "rolling-kick",
    "headbutt",
    "horn-attack",
    "fury-attack",
    "horn-drill",
    "tackle",
    "body-slam",
    "wrap",
    "take-down",
    "thrash",
    "double-edge",
    "bite",
    "peck",
    "drill-peck",
    "submission",
    "low-kick",
    "counter",
    "seismic-toss",
    "strength",
    "petal-dance",
    "dig",
    "quick-attack",
    "rage",
    "bide",
    "lick",
    "waterfall",
    "clamp",
    "skull-bash",
    "constrict",
    "hi-jump-kick",
    "leech-life",
    "dizzy-punch",
    "crabhammer",
    "fury-swipes",
    "hyper-fang",
    "super-fang",
    "slash",
    "struggle",
    "triple-kick",
    "thief",
    "flame-wheel",
    "flail",
    "reversal",
    "mach-punch",
    "outrage",
    "rollout",
    "false-swipe",
    "spark",
    "fury-cutter",
    "steel-wing",
    "return",
    "frustration",
    "dynamic-punch",
    "megahorn",
    "pursuit",
    "rapid-spin",
    "iron-tail",
    "metal-claw",
    "vital-throw",
    "cross-chop",
    "crunch",
    "extreme-speed",
    "ancient-power",
    "rock-smash",
    "facade",
    "focus-punch",
    "smelling-salt",
    "superpower",
    "revenge",
    "brick-break",
    "knock-off",
    "endeavor",
    "dive",
    "arm-thrust",
    "blaze-kick",
    "ice-ball",
    "needle-arm",
    "poison-fang",
    "crush-claw",
    "meteor-mash",
    "astonish",
    "overheat",
    "shadow-punch",
    "sky-uppercut",
    "aerial-ace",
    "dragon-claw",
    "bounce",
    "poison-tail",
    "volt-tackle",
    "leaf-blade",
}


def move_makes_contact(move: BattleMove) -> bool:
    return normalize_move_name(move.name) in CONTACT_MOVES


def move_is_high_critical(move: BattleMove) -> bool:
    return normalize_move_name(move.name) in HIGH_CRITICAL_MOVES
